### ISSUE TITLE
Implement Docker

### ISSUE THREAD

**Issue by FlopiVG** [FlopiVG/basic-multiplayer#4]
Run app with docker to run **npm start** inside the container

User docker-compose.yml to run more easily the App

**Comment by sergioarroyop** [comment]
Hey! Do you need help with this one?

**Comment by FlopiVG** [comment]
Yes,:smile:

**Comment by sergioarroyop** [comment]
Take a look! :smile_cat:

**Comment by FlopiVG** [comment]
Nice :)

**Comment by FlopiVG** [comment]
#6 closed
